#!/bin/sh 
# $1 - SR, CR or VR

#Background Model Fit 
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/DataRootFiles/rereco-CDEF-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o  results/DataDrivenBkgdModel-$1-3j/BernsteinEffProd/200to500 --fit_min 200 --fit_max 500 --nbins 30 --type background --model berneffprod
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/DataRootFiles/rereco-CDEF-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o  results/DataDrivenBkgdModel-$1-3j/ExtNovoEffProd/260to785 --fit_min 260 --fit_max 785 --nbins 30 --type background --model extnovoeffprod
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/DataRootFiles/rereco-CDEF-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o  results/DataDrivenBkgdModel-$1-3j/Novosibirsk/390to1270 --fit_min 390 --fit_max 1270 --nbins 30 --type background --model mynovosibirsk
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/DataRootFiles/rereco-CDEF-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o  results/DataDrivenBkgdModel-$1-3j/Novosibirsk/500to2000 --fit_min 500 --fit_max 2000 --nbins 30 --type background --model mynovosibirsk

#Signal Model Fit 
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-300-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-300-NLO-deep-$1-3j --fit_min 200 --fit_max 500 --nbins 30 --type signal --model doublegausexp
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-350-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-350-NLO-deep-$1-3j --fit_min 200 --fit_max 500 --nbins 30 --type signal --model doublegausexp
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-400-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-400-NLO-deep-$1-3j --fit_min 200 --fit_max 500 --nbins 30 --type signal --model doublegausexp
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-450-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-450-NLO-deep-$1-3j --fit_min 200 --fit_max 500 --nbins 30 --type signal --model doublegausexp
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-500-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-500-NLO-deep-$1-3j --fit_min 260 --fit_max 785 --nbins 52 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-600-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-600-NLO-deep-$1-3j --fit_min 260 --fit_max 785 --nbins 52 --type signal --model quadgausexp
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-700-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-700-NLO-deep-$1-3j --fit_min 390 --fit_max 1270 --nbins 44 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-800-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-800-NLO-deep-$1-3j --fit_min 390 --fit_max 1270 --nbins 44 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-900-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-900-NLO-deep-$1-3j --fit_min 390 --fit_max 1270 --nbins 44 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-1000-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-1000-NLO-deep-$1-3j --fit_min 500 --fit_max 2000 --nbins 60 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-1200-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-1200-NLO-deep-$1-3j --fit_min 500 --fit_max 2000 --nbins 60 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-1400-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-1400-NLO-deep-$1-3j --fit_min 500 --fit_max 2000 --nbins 60 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-1600-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-1600-NLO-deep-$1-3j --fit_min 500 --fit_max 2000 --nbins 60 --type signal --model bukin

#Signal Model Fit (alternative functions)
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-300-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-300-NLO-deep-$1-3j-bukin --fit_min 200 --fit_max 500 --nbins 30 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-350-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-350-NLO-deep-$1-3j-bukin --fit_min 200 --fit_max 500 --nbins 30 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-400-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-400-NLO-deep-$1-3j-bukin --fit_min 200 --fit_max 500 --nbins 30 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-450-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-450-NLO-deep-$1-3j-bukin --fit_min 200 --fit_max 500 --nbins 30 --type signal --model bukin
FitModel -t /nfs/dust/cms/user/consuegs/Analyses/Hbb_MSSM/analysis-mssmhbb/test/Hbb_MSSM/Run2017/SignalRootFiles/mc-sig-600-NLO-deep-$1-3j.root --input_tree MssmHbb_13TeV --input_data mbb --input_weight weight -o results/mc-sig-600-NLO-deep-$1-3j-bukin --fit_min 260 --fit_max 785 --nbins 52 --type signal --model bukin
